### ISSUE TITLE
line number overlapped

### ISSUE THREAD

**Issue by bataliero** [FelisDiligens/joplin-plugin-cmoptions#4] opened 2023-09-15 07:24 UTC
Hi, 

UPDATE:
"Fix line numbers" option solves the problem!
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/17815959/ebef7732-c3be-4ed0-a46c-dd9614bc883f)

---

Depending on a size of "Body" window - left column with line number overlaps the content of the note or is outside of vertical gray bar.

I have no other plugins enabled. 
Reinstalling (Linux desktop) Joplin from `2.8.8` to `2.12.17` did not help.

![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/17815959/71330f27-c20c-4a75-adf0-e5cc28d52875)
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/17815959/cd3a8562-b073-4b9e-b5bd-4e78f9da0619)
![image](https://github.com/FelisDiligens/joplin-plugin-cmoptions/assets/17815959/e8ae1d51-4934-4023-8b84-30de0192b338)

Thanks

**Comment by FelisDiligens** [comment] 2023-09-16 16:14
Hi, glad to see the CSS fix did the trick.
Closing the issue, duplicate of #3

**Closed as completed by FelisDiligens** 2023-09-16 16:14 UTC
